/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILidoProtocol,
  ILidoProtocolInterface,
} from "../../../../../contracts/adapters/lido/interfaces/ILidoProtocol";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_sharesAmount",
        type: "uint256",
      },
    ],
    name: "getPooledEthByShares",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isStakingPaused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_referral",
        type: "address",
      },
    ],
    name: "submit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ILidoProtocol__factory {
  static readonly abi = _abi;
  static createInterface(): ILidoProtocolInterface {
    return new Interface(_abi) as ILidoProtocolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILidoProtocol {
    return new Contract(address, _abi, runner) as unknown as ILidoProtocol;
  }
}
