/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { StaderAdapter__factory } from "./StaderAdapter__factory";
