/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface EtherFiMockInterface extends Interface {
  getFunction(
    nameOrSignature: "depositWithERC20" | "eETH" | "stETH" | "tokensPerStEth"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositWithERC20",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "eETH", values?: undefined): string;
  encodeFunctionData(functionFragment: "stETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokensPerStEth",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "depositWithERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "eETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokensPerStEth",
    data: BytesLike
  ): Result;
}

export interface EtherFiMock extends BaseContract {
  connect(runner?: ContractRunner | null): EtherFiMock;
  waitForDeployment(): Promise<this>;

  interface: EtherFiMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositWithERC20: TypedContractMethod<
    [arg0: AddressLike, _amount: BigNumberish, arg2: AddressLike],
    [bigint],
    "nonpayable"
  >;

  eETH: TypedContractMethod<[], [string], "view">;

  stETH: TypedContractMethod<[], [string], "view">;

  tokensPerStEth: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositWithERC20"
  ): TypedContractMethod<
    [arg0: AddressLike, _amount: BigNumberish, arg2: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokensPerStEth"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
