/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IKelpProtocolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositAsset"
      | "getAssetCurrentLimit"
      | "getRsETHAmountToMint"
      | "minAmountToDeposit"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositAsset",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetCurrentLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRsETHAmountToMint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minAmountToDeposit",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "depositAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetCurrentLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRsETHAmountToMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minAmountToDeposit",
    data: BytesLike
  ): Result;
}

export interface IKelpProtocol extends BaseContract {
  connect(runner?: ContractRunner | null): IKelpProtocol;
  waitForDeployment(): Promise<this>;

  interface: IKelpProtocolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositAsset: TypedContractMethod<
    [
      asset: AddressLike,
      depositAmount: BigNumberish,
      minRSETHAmountExpected: BigNumberish,
      referralId: string
    ],
    [void],
    "nonpayable"
  >;

  getAssetCurrentLimit: TypedContractMethod<
    [asset: AddressLike],
    [bigint],
    "view"
  >;

  getRsETHAmountToMint: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  minAmountToDeposit: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositAsset"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      depositAmount: BigNumberish,
      minRSETHAmountExpected: BigNumberish,
      referralId: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAssetCurrentLimit"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRsETHAmountToMint"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "minAmountToDeposit"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
