/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StrSimpleReStaking } from "./StrSimpleReStaking";
export type { StrSimpleStaking } from "./StrSimpleStaking";
